%Filtro pasa banda, diseñado con Filter Designer de la Signal Processing Toolbox
%Requiere como parámetros la frecuencia de muestreo (Fs) y las frecuencias
%de corte (Fc1,Fc2).

function Hd = filtro_pasa_banda(Fs,Fc1,Fc2)
%FB Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = Fs;  % Sampling Frequency

N   = 20;   % Order
Fc1 = Fc1;  % First Cutoff Frequency
Fc2 = Fc2;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');